---
- hosts: all
  gather_facts: false
  tasks:
  - name: check for subscription status
    block:
      - name: check status
        command: /usr/bin/subscription-manager status
        become: yes
    rescue:
      - debug:
          msg: 'I caught an error, can do stuff here to fix it, :-)'
