---
- hosts: all
  gather_facts: false
  tasks:
  - name: check for subscription status
    block:
      - name: check status
        command: /usr/bin/subscription-manager status
        become: yes
    rescue:
      - debug:
          msg: "failed result: {{ ansible_failed_result }}"
