---
- hosts: all
  gather_facts: false
  tasks:
  - name: check for subscription status
    block:
      - command: /usr/bin/subscription-manager status
        become: yes
        register: result
        ignore_errors: yes
        changed_when: False
        
      rescue:
        -fail:
            msg: "{{ result.stdout_lines }}"
          
