---
- hosts: all
  gather_facts: false
  tasks:
    - command: /usr/bin/subscription-manager status
      become: yes
      register: result
      failed_when: result.rc >= 1
    
    - debug:
        msg: "{{ result }}"
