---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Get Running instance Info
      ec2_instance_info:
        region: us-east-1
      register: ec2info 
    - name: Print info
      debug: var="ec2info.instances"
